title: brightiny9
description: "What we're building, compared side by side with similar products"
url: https://brightiny9.github.io
baseurl: ""
lang: en
author:
  name: brightiny9
remote_theme: chesterhow/tale
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - README.md
